-- =====================================================================
-- Skill 2 · interaction-intel — FALLBACK for accounts/regions without AI_CLASSIFY / AI_COMPLETE.
-- Uses the legacy, GA-everywhere functions:
--   SNOWFLAKE.CORTEX.SENTIMENT, SNOWFLAKE.CORTEX.CLASSIFY_TEXT, SNOWFLAKE.CORTEX.SUMMARIZE
-- Same output table and columns as interaction_intel.sql.
-- =====================================================================
USE WAREHOUSE POLICYPULSE_WH;
USE SCHEMA POLICYPULSE.CURATED;

CREATE TABLE IF NOT EXISTS CURATED.INTERACTION_INSIGHTS (
  TRANSCRIPT_ID VARCHAR, CUSTOMER_ID VARCHAR, POLICY_ID VARCHAR, CALL_TS TIMESTAMP_NTZ, AGENT_ID VARCHAR,
  CUSTOMER_TEXT VARCHAR, SENTIMENT_SCORE FLOAT, SENTIMENT_LABEL VARCHAR, PRIMARY_INTENT VARCHAR,
  SUMMARY VARCHAR, TRANSCRIPT_TEXT VARCHAR, ENRICHED_BY VARCHAR, ENRICHED_AT TIMESTAMP_NTZ
);

INSERT INTO CURATED.INTERACTION_INSIGHTS
WITH todo AS (
  SELECT t.* FROM RAW.CALL_TRANSCRIPTS t
  WHERE NOT EXISTS (SELECT 1 FROM CURATED.INTERACTION_INSIGHTS i WHERE i.TRANSCRIPT_ID = t.TRANSCRIPT_ID)
),
cust_text AS (
  SELECT t.TRANSCRIPT_ID,
         LISTAGG(TRIM(SUBSTR(TRIM(s.VALUE), 10)), ' ') WITHIN GROUP (ORDER BY s.INDEX) AS CUSTOMER_TEXT
  FROM todo t, LATERAL SPLIT_TO_TABLE(t.TRANSCRIPT_TEXT, '\n') s
  WHERE STARTSWITH(TRIM(s.VALUE), 'Customer:')
  GROUP BY t.TRANSCRIPT_ID
),
enriched AS (
  SELECT t.TRANSCRIPT_ID, t.CUSTOMER_ID, t.POLICY_ID, t.CALL_TS, t.AGENT_ID, ct.CUSTOMER_TEXT, t.TRANSCRIPT_TEXT,
         SNOWFLAKE.CORTEX.SENTIMENT(ct.CUSTOMER_TEXT) AS SENTIMENT_SCORE,
         SNOWFLAKE.CORTEX.CLASSIFY_TEXT(
           ct.CUSTOMER_TEXT,
           ['claim_issue', 'price_concern', 'cancellation_intent', 'upsell_interest', 'service_praise', 'general_service'],
           {'task_description': 'Primary reason an insurance customer called the call centre'}
         ):label::VARCHAR AS PRIMARY_INTENT,
         SNOWFLAKE.CORTEX.SUMMARIZE(t.TRANSCRIPT_TEXT) AS SUMMARY
  FROM todo t LEFT JOIN cust_text ct ON ct.TRANSCRIPT_ID = t.TRANSCRIPT_ID
)
SELECT TRANSCRIPT_ID, CUSTOMER_ID, POLICY_ID, CALL_TS, AGENT_ID, CUSTOMER_TEXT,
       ROUND(SENTIMENT_SCORE, 3),
       CASE WHEN SENTIMENT_SCORE <= -0.25 THEN 'negative' WHEN SENTIMENT_SCORE >= 0.25 THEN 'positive' ELSE 'neutral' END,
       PRIMARY_INTENT, SUMMARY, TRANSCRIPT_TEXT,
       'CORTEX.SENTIMENT + CLASSIFY_TEXT + SUMMARIZE (fallback)', CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
FROM enriched;

SELECT COUNT(*) AS TRANSCRIPTS_ENRICHED,
       ROUND(AVG(IFF(i.PRIMARY_INTENT = l.TRUE_INTENT, 1, 0)) * 100, 1) AS INTENT_ACCURACY_PCT
FROM CURATED.INTERACTION_INSIGHTS i LEFT JOIN RAW.EVAL_TRANSCRIPT_LABELS l USING (TRANSCRIPT_ID);
