[theme]
base = "light"
primaryColor = "#1c5cab"
backgroundColor = "#f9f9f7"
secondaryBackgroundColor = "#f0efec"
textColor = "#0b0b0b"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
